"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
import cloudinary
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--_b(vgzqe$t!4hvwxlel8j*ctz&$tirb^4hfxe(7x+)ood^%k('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne', #Web socket 
    'admins',
    'users',
    'users_cart',
    'users_order',
    'users_profile',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework.authtoken',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'django_celery_results',
    'django_celery_beat',
    'mail_senter',
    'user_feedback',
    'chatbot',
    'cloudinary_storage',
]
SITE_ID =1
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]


REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'rest_framework_json_api.exceptions.exception_handler',
    
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    
}
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'backend.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = "backend.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


SWAGGER_SETTINGS = {
        "SECURITY_DEFINITIONS": {
            "Token": {"type": "apiKey", "name": "Authorization", "in": "header"},
            "Basic": {"type": "basic"},
        }
    }


CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/kolkata'
CELERY_RESULT_BACKEND = 'django-db'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'


#MAILJET
# MAILJET_API_KEY = '6f26d527d0db808f8ab9717a9888c23d'
# MAILJET_API_SECRET = '55ba21bc94bb05ad9bd44fe06155f01a'



# FRONTEND URL
FRONTEND_URL = "https://kl-electronics.com"


# TOken expire 
PASSWORD_RESET_TIMEOUT = 1 * 60 * 60  



# Default Image 
DEFAULT_IMAGE = "http://res.cloudinary.com/dg3m2vvvs/image/upload/v1710835028/vtsipjaola9uaeldow5b.jpg"
DEFAULT_HIGHLIGHT_IMAGE = "http://res.cloudinary.com/dg3m2vvvs/image/upload/v1710840141/categories/images/lmur2p2oykqbhvdhkg9m.jpg"



# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': 'dg3m2vvvs',
#     'API_KEY': '116248533516963',
#     'API_SECRET': '5qDtWr_8eUwUTN9jzEmwOUBiVS8'
# }
cloudinary.config( 
cloud_name = "dg3m2vvvs",
api_key = "116248533516963",
api_secret = "5qDtWr_8eUwUTN9jzEmwOUBiVS8"
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,"media")
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'    

ORDER_STATUS_IMAGE_URLS_COLOR={
    "received":"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/xobjbpwwbk8iubmbnqlj",
    'confirmed':"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/bmz9bv7ywixx7tl6ehqe",
    'shipped':"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/hx8hizxewloycdf5pp1o",
    'completed':"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/wisvgbvgh2zt1jeu6vj6",
    "cancelled":"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/kiutpk4sb8kk0azjsyqy",
    "request_received":"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/xobjbpwwbk8iubmbnqlj",
    'request_confirmed':"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/bmz9bv7ywixx7tl6ehqe",
    'product_received':"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/qitokwagwwkn1vhxbnkc",
    'replacement':"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/syqhb5nrnmfrkgjrj4dl",
    'resolved':"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/aeo4fuvitvm7iwu06mzk",
    'cancelled':"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/kiutpk4sb8kk0azjsyqy",
    'refund':"https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/js5n1kzx7h2pdfrnmlfm",
}
ORDER_ICON_IMAGE_GREY ="https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/m5iznx2lbsagjfzdaidk" 
ORDER_ICON_IMAGE_COLOR ="https://res.cloudinary.com/dg3m2vvvs/image/upload/order_images/kjhcwymaziilvixmk4fs" 

PAYMENT_MODE_IMAGE = {
    "cash" :"https://res.cloudinary.com/dg3m2vvvs/image/upload/payment_methods/a3mquuopmqjffe7dudap",
    "online" :"https://res.cloudinary.com/dg3m2vvvs/image/upload/payment_methods/ij3mkph6sojlmnbvowlp",
    "bank" :"https://res.cloudinary.com/dg3m2vvvs/image/upload/payment_methods/xe61hohxszf1lmrucdm6"
}


SHOP_URL = "https://youtube.com"
SITE_LOGO_WITH_NAME = "https://res.cloudinary.com/dg3m2vvvs/image/upload/uomsaio2babjmbuj1yav" 
SITE_LOGO = "https://res.cloudinary.com/dg3m2vvvs/image/upload/mqpfurht51btcvqoagxk" 