# Generated by Django 4.2.10 on 2024-04-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_rename_emailprovider_adminemailprovider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMode',
            new_name='AdminPaymentMode',
        ),
    ]
